name: Build and Tag

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "docs/**"
      - ".gitignore"
      - "Claude.md"
  workflow_dispatch:

env:
  SKIP_CI: ${{ contains(github.event.head_commit.message, '[skip ci]') }}

jobs:
  build-and-tag:
    permissions:
      contents: write
      id-token: write
    runs-on: windows-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Install Electron Builder
        run: npm install -g electron-builder

      - name: Check for application icon
        run: |
          if (!(Test-Path "assets\icon.png")) {
            Write-Host "Warning: No application icon found at assets\icon.png"
            Write-Host "A default icon will be used. Add your icon to assets\icon.png for branding."
          } else {
            Write-Host "Application icon found at assets\icon.png"
          }
        shell: powershell

      - name: Package Electron app
        run: electron-builder --win --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate build tag and get version
        id: build-tag
        run: |
          $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
          $commitHash = git rev-parse --short HEAD
          $buildTag = "build-$timestamp-$commitHash"
          $packageJson = Get-Content package.json | ConvertFrom-Json
          $version = $packageJson.version
          echo "tag=$buildTag" >> $env:GITHUB_OUTPUT
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "Generated build tag: $buildTag"
          echo "Package version: $version"
        shell: powershell

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create and push tag
        run: |
          $buildVersion = "${{ steps.build-tag.outputs.version }}"
          git tag $buildVersion -m "Release $buildVersion"
          git push origin $buildVersion
          echo "Created and pushed tag: $buildVersion"
        shell: powershell
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.build-tag.outputs.tag }}
          name: "Build ${{ steps.build-tag.outputs.tag }}"
          body: |
            ## Automated Build Release

            **Build Information:**
            - Version: ${{ steps.build-tag.outputs.version }}
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref_name }}
            - Timestamp: ${{ steps.build-tag.outputs.tag }}

            **Included Files:**
            - Windows Installer - `Velocity.Launcher-${{ steps.build-tag.outputs.version }}-x64.exe`
            - Portable Executable - `Velocity.Launcher-${{ steps.build-tag.outputs.version }}-portable.exe`
            - Zip Archive - `Velocity.Launcher-${{ steps.build-tag.outputs.version }}-x64.zip`

            This is an automated build from the CI/CD pipeline.

            ### Download Instructions:
            - **For most users**: Download the Windows Installer
            - **For portable use**: Download the Portable executable
            - **For manual extraction**: Download the Zip archive
          draft: false
          prerelease: true
          files: |
            dist/VelocityLauncher-${{ steps.build-tag.outputs.version }}-x64.exe
            dist/VelocityLauncher-${{ steps.build-tag.outputs.version }}-portable.exe
            dist/VelocityLauncher-${{ steps.build-tag.outputs.version }}-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts (backup)
        uses: actions/upload-artifact@v4
        with:
          name: velocity-launcher-${{ steps.build-tag.outputs.tag }}
          path: |
            dist/*.exe
            dist/*.zip
            dist/*.msi
          retention-days: 30
